apiVersion: v1
kind: Service
metadata:
  name: my-react-app
  labels:
    app: my-react-app
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: my-react-app
  type: LoadBalancer
